import { Injectable } from '@angular/core';

export type MemberRole = 'president' | 'advisor';
export type RoleFilter = 'all' | MemberRole;

export interface Member {
  name: string;
  title: string;
  titleKey: string;
  email: string;
  image: string;
  role: MemberRole;
  slug: string;
  office: string;
  officeKey: string;
  summary: string;
  summaryKey: string;
}

@Injectable({ providedIn: 'root' })
export class MemberService {
  readonly members: Member[] = [
    {
      name: 'NSENSELE WA NSENSELE Brigitte',
      title: 'President',
        titleKey: 'member.title.president',
      email: 'nsensele@conseildetatrdc.com',
      image:
        'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1772555485/Brigitte_NSENSELE_wa_NSENSELE_OK.jpg_ndsjzg.jpg',
      role: 'president',
      slug: 'nsensele-wa-nsensele-brigitte',
      office: 'STATE COUNCIL',
        officeKey: 'member.office.stateCouncil',
      summary: 'Leads judicial coordination and ensures consistent application of State Council jurisprudence across chambers.',
      summaryKey: 'member.summary.nsensele',
    },
    {
      name: 'BOMBULU BOMBONGO Simon Dieudonné',
        titleKey: 'member.title.president',
      title: 'President',
      email: 'bombulu@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1773132546/40x50_BOMBOLU_copie.jpg_lj7rdp.jpg',
      role: 'president',
      slug: 'bombulu-bombongo-simon-dieudonne',
        officeKey: 'member.office.stateCouncil',
      office: 'STATE COUNCIL',
      summary: 'Oversees appellate coordination and guides chamber leadership on procedural standards.',
      summaryKey: 'member.summary.bombulu',
    },
    {
      name: 'NDALA MUSWAMBA Marie Louise',
        titleKey: 'member.title.president',
      title: 'President',
      email: 'ndala@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1775670049/vecteezy_user-profile-vector-flat-illustration-avatar-person-icon_37336395_ukit5u.jpg',
      role: 'president',
      slug: 'ndala-muswamba-marie-louise',
        officeKey: 'member.office.stateCouncil',
        summaryKey: 'member.summary.ndala',
      office: 'STATE COUNCIL',
      summary: 'Supports strategic planning and supervises policy alignment across the Court’s divisions.'
    },
    {
      name: 'MASANI MATSHI Hippolyte',
        titleKey: 'member.title.president',
      title: 'President',
      email: 'masani@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1772556705/PRES_MASANI_40x50.jpg_ast5mq.jpg',
      role: 'president',
      slug: 'masani-matshi-hippolyte',
        officeKey: 'member.office.stateCouncil',
      office: 'STATE COUNCIL',
      summary: 'Coordinates chamber operations and drives procedural modernization initiatives.',
      summaryKey: 'member.summary.masani',
    },
    {
      name: 'FUNGA MOLIMA MWATA Evariste Prince',
        titleKey: 'member.title.president',
      title: 'President',
      email: 'funga@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1775670049/vecteezy_user-profile-vector-flat-illustration-avatar-person-icon_37336395_ukit5u.jpg',
      role: 'president',
      slug: 'funga-molima-mwata-evariste-prince',
        officeKey: 'member.office.stateCouncil',
      office: 'STATE COUNCIL',
      summary: 'Guides jurisprudential review and ensures consistency across legal interpretations.',
      summaryKey: 'member.summary.funga',
    },
    {
      name: 'ESAMBO KANGASHE Jean Louis',
        titleKey: 'member.title.president',
      title: 'President',
      email: 'esambo@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1775670049/vecteezy_user-profile-vector-flat-illustration-avatar-person-icon_37336395_ukit5u.jpg',
      role: 'president',
      slug: 'esambo-kangashe-jean-louis',
        officeKey: 'member.office.stateCouncil',
      office: 'STATE COUNCIL',
      summary: 'Leads training oversight and supports institutional capacity building.',
      summaryKey: 'member.summary.esambo',
    },
    {
      name: 'MALENGA MINGA Modeste',
        titleKey: 'member.title.president',
      title: 'President',
      email: 'malenga@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1776204246/MALENGA_40x50.jpg_yyuzl3.jpg',
      role: 'president',
      slug: 'malenga-minga-modeste',
        officeKey: 'member.office.stateCouncil',
      office: 'STATE COUNCIL',
      summary: 'Oversees chamber quality assurance and jurisprudence harmonization.',
      summaryKey: 'member.summary.malenga',
    },
    {
      name: 'ABDALA MBOKAMIBA Remy',
        titleKey: 'member.title.president',
      title: 'President',
      email: 'abdala@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1776599568/PRES_ABDALA_MBOKAMIBA_REMY_copie.jpg_1_ywkylj.jpg',
      role: 'president',
      slug: 'abdala-mbokamiba-remy',
        officeKey: 'member.office.stateCouncil',
      office: 'STATE COUNCIL',
      summary: 'Coordinates outreach with legal stakeholders and ensures protocol adherence.',
      summaryKey: 'member.summary.abdala',
    },
    {
      name: 'KIBWE MUTER Eugène',
        titleKey: 'member.title.president',
      title: 'President',
      email: 'kibwe@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1772556921/Eug%C3%A8ne_KIBWE_MUTER.jpg_bacl4e.jpg',
      role: 'president',
      slug: 'kibwe-muter-eugene',
        officeKey: 'member.office.stateCouncil',
      office: 'STATE COUNCIL',
      summary: 'Supports appellate governance and strengthens cross-chamber institutional coordination.',
      summaryKey: 'member.summary.kibwe',
    },
    {
      name: 'BULAMBO BAKONGA Beniamin',
        titleKey: 'member.title.president',
      title: 'President',
      email: 'bulambo@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1775670049/vecteezy_user-profile-vector-flat-illustration-avatar-person-icon_37336395_ukit5u.jpg',
      role: 'president',
      slug: 'bulambo-bakonga-beniamin',
        officeKey: 'member.office.stateCouncil',
      office: 'STATE COUNCIL',
      summary: 'Drives chamber-level governance and contributes to procedural consistency across matters.',
      summaryKey: 'member.summary.bulambo',
    },
    {
      name: 'TSHIBOLA BIDILUKINI Antoine',
      title: 'Advisor',
        titleKey: 'member.title.advisor',
      email: 'tshibola@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1776601097/CONS_TSHIBOLA_BIDILUKINI_ANTOINE_copie.jpg_1_spfgik.jpg',
      role: 'advisor',
      slug: 'tshibola-bidilukini-antoine',
        officeKey: 'member.office.stateCouncil',
      office: 'STATE COUNCIL',
      summary: 'Provides advisory support on administrative and judicial matters.',
      summaryKey: 'member.summary.advisor',
    },
    {
      name: 'KAHUNGU ZAMBA Félix',
        titleKey: 'member.title.advisor',
      title: 'Advisor',
      email: 'kahungu@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1773133094/KAHUNGU_30x40_copie22.jpg_dra7jd.jpg',
      role: 'advisor',
      slug: 'kahungu-zamba-felix',
        officeKey: 'member.office.stateCouncil',
        summaryKey: 'member.summary.advisor',
      office: 'STATE COUNCIL',
      summary: 'Provides advisory support on administrative and judicial matters.'
    },
    {
      name: 'BAHATI MAIMOTO Roger',
        titleKey: 'member.title.advisor',
      title: 'Advisor',
      email: 'bahati@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1776204001/CONSEILLER_BAHATI_MAIMOTO_ROGER.jpg_fjvwlv.jpg',
      role: 'advisor',
      slug: 'bahati-maimoto-roger',
        officeKey: 'member.office.stateCouncil',
        summaryKey: 'member.summary.advisor',
      office: 'STATE COUNCIL',
      summary: 'Provides advisory support on administrative and judicial matters.'
    },
    {
      name: 'SIBU MATUBUKA René',
        titleKey: 'member.title.advisor',
      title: 'Advisor',
      email: 'sibu@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1775670049/vecteezy_user-profile-vector-flat-illustration-avatar-person-icon_37336395_ukit5u.jpg',
      role: 'advisor',
      slug: 'sibu-matubuka-rene',
        officeKey: 'member.office.stateCouncil',
        summaryKey: 'member.summary.advisor',
      office: 'STATE COUNCIL',
      summary: 'Provides advisory support on administrative and judicial matters.'
    },
    {
      name: 'CAKWANGASHA KABWENGA Jean-Pierre',
        titleKey: 'member.title.advisor',
      title: 'Advisor',
      email: 'cakwangasha@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1775670049/vecteezy_user-profile-vector-flat-illustration-avatar-person-icon_37336395_ukit5u.jpg',
      role: 'advisor',
      slug: 'cakwangasha-kabwenga-jean-pierre',
        officeKey: 'member.office.stateCouncil',
        summaryKey: 'member.summary.advisor',
      office: 'STATE COUNCIL',
      summary: 'Provides advisory support on administrative and judicial matters.'
    },
    {
      name: 'AYANGASOBE BAMBABALE Blaise',
        titleKey: 'member.title.advisor',
      title: 'Advisor',
      email: 'ayangasobe@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1776203827/AYANGASOBE_BAMBALE_Blaise.jpg_jatkje.jpg',
      role: 'advisor',
      slug: 'ayangasobe-bambabale-blaise',
        officeKey: 'member.office.stateCouncil',
        summaryKey: 'member.summary.advisor',
      office: 'STATE COUNCIL',
      summary: 'Provides advisory support on administrative and judicial matters.'
    },
    {
      name: 'KITENGE NDIBU John',
        titleKey: 'member.title.advisor',
      title: 'Advisor',
      email: 'kitenge@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1775670049/vecteezy_user-profile-vector-flat-illustration-avatar-person-icon_37336395_ukit5u.jpg',
      role: 'advisor',
      slug: 'kitenge-ndibu-john',
        officeKey: 'member.office.stateCouncil',
        summaryKey: 'member.summary.advisor',
      office: 'STATE COUNCIL',
      summary: 'Provides advisory support on administrative and judicial matters.'
    },
    {
      name: 'BADIBANGA ILUNGA Jean',
        titleKey: 'member.title.advisor',
      title: 'Advisor',
      email: 'badibanga@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1775670049/vecteezy_user-profile-vector-flat-illustration-avatar-person-icon_37336395_ukit5u.jpg',
      role: 'advisor',
      slug: 'badibanga-ilunga-jean',
        officeKey: 'member.office.stateCouncil',
        summaryKey: 'member.summary.advisor',
      office: 'STATE COUNCIL',
      summary: 'Provides advisory support on administrative and judicial matters.'
    },
    {
      name: 'KANZA MAKOKA Joseph',
        titleKey: 'member.title.advisor',
      title: 'Advisor',
      email: 'kanza@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1777070512/CONS_KANZA_MAKOKA_JOSEPH_copie.jpg_1_ctcw5q.jpg',
      role: 'advisor',
      slug: 'kanza-makoka-joseph',
        officeKey: 'member.office.stateCouncil',
        summaryKey: 'member.summary.advisor',
      office: 'STATE COUNCIL',
      summary: 'Provides advisory support on administrative and judicial matters.'
    },
    {
      name: 'KATAMBE MALIPO Gérard',
        titleKey: 'member.title.advisor',
      title: 'Advisor',
      email: 'katambe@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1773133247/40x50.jpg_guvc1v.jpg',
      role: 'advisor',
      slug: 'katambe-malipo-gerard',
        officeKey: 'member.office.stateCouncil',
        summaryKey: 'member.summary.advisor',
      office: 'STATE COUNCIL',
      summary: 'Provides advisory support on administrative and judicial matters.'
    },
    {
      name: 'LEMBLEMBE N\'KASCHAMA Guérin Emmanuel',
        titleKey: 'member.title.advisor',
      title: 'Advisor',
      email: 'lemblembe@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1776600547/CONS_LEMBELEMBE_copie.jpg_1_ttyqir.jpg',
      role: 'advisor',
      slug: 'lemblembe-n-kaschama-guerin-emmanuel',
        officeKey: 'member.office.stateCouncil',
        summaryKey: 'member.summary.advisor',
      office: 'STATE COUNCIL',
      summary: 'Provides advisory support on administrative and judicial matters.'
    },
    {
      name: 'LUSHULE BASHOMEKA Déogratias',
        titleKey: 'member.title.advisor',
      title: 'Advisor',
      email: 'lushule@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1776600405/CONS._LUSHULE_BASHOMEKA_DEO_copie.jpg_1_vfnzwa.jpg',
      role: 'advisor',
      slug: 'lushule-bashomeka-deogratias',
        officeKey: 'member.office.stateCouncil',
        summaryKey: 'member.summary.advisor',
      office: 'STATE COUNCIL',
      summary: 'Provides advisory support on administrative and judicial matters.'
    },
    {
      name: 'MAYENGO LUZIMBUKI Aimé',
        titleKey: 'member.title.advisor',
      title: 'Advisor',
      email: 'mayengo@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1776599990/CONS._MAYENGO_LUZIMU_copie.jpg_1_iykqh8.jpg',
      role: 'advisor',
      slug: 'mayengo-luzimbuki-aime',
        officeKey: 'member.office.stateCouncil',
        summaryKey: 'member.summary.advisor',
      office: 'STATE COUNCIL',
      summary: 'Provides advisory support on administrative and judicial matters.'
    },
    {
      name: 'Mme MONGU NKANGA Marie-Louise',
        titleKey: 'member.title.advisor',
      title: 'Advisor',
      email: 'mongu@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1776770563/CONS._MONGU_NKANGA_copie.jpg_1_pda3zf.jpg',
      role: 'advisor',
      slug: 'mme-mongu-nkanga-marie-louise',
        officeKey: 'member.office.stateCouncil',
        summaryKey: 'member.summary.advisor',
      office: 'STATE COUNCIL',
      summary: 'Provides advisory support on administrative and judicial matters.'
    },
    {
      name: 'MUDINDAMBI NAWENA Julien',
        titleKey: 'member.title.advisor',
      title: 'Advisor',
      email: 'mudindambi@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1776597596/CONS._MUDINDAMBI_NAWENA_JULIEN.jpg_1_vzzcbk.jpg',
      role: 'advisor',
      slug: 'mudindambi-nawena-julien',
        officeKey: 'member.office.stateCouncil',
        summaryKey: 'member.summary.advisor',
      office: 'STATE COUNCIL',
      summary: 'Provides advisory support on administrative and judicial matters.'
    },
    {
      name: 'KOURA MFUMANKIE Emmanuel',
        titleKey: 'member.title.advisor',
      title: 'Advisor',
      email: 'koura@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1773133441/40x50_copie.jpg_gs0g6x.jpg',
      role: 'advisor',
      slug: 'koura-mfumankie-emmanuel',
        officeKey: 'member.office.stateCouncil',
        summaryKey: 'member.summary.advisor',
      office: 'STATE COUNCIL',
      summary: 'Provides advisory support on administrative and judicial matters.'
    },
    {
      name: 'NTUMBA MUSUKA Zacharie',
        titleKey: 'member.title.advisor',
      title: 'Advisor',
      email: 'ntumba.musuka@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1777070612/CONS_NTUMBA_MUSUKA_copie.jpg_1_dwm6gb.jpg',
      role: 'advisor',
      slug: 'ntumba-musuka-zacharie',
        officeKey: 'member.office.stateCouncil',
        summaryKey: 'member.summary.advisor',
      office: 'STATE COUNCIL',
      summary: 'Provides advisory support on administrative and judicial matters.'
    },
    {
      name: 'NTUMBA MANDE Enoch',
        titleKey: 'member.title.advisor',
      title: 'Advisor',
      email: 'ntumba.mande@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1777078279/CONS_NTUMBA_MANDE_copie.jpg_1_jgbgor.jpg',
      role: 'advisor',
      slug: 'ntumba-mande-enoch',
        officeKey: 'member.office.stateCouncil',
        summaryKey: 'member.summary.advisor',
      office: 'STATE COUNCIL',
      summary: 'Provides advisory support on administrative and judicial matters.'
    },
    {
      name: 'WANE BAMEME Bienvenu',
        titleKey: 'member.title.advisor',
      title: 'Advisor',
      email: 'wane@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1776600744/CONS._WANE_BAMEME_BIENVENU.jpg_1_esxchc.jpg',
      role: 'advisor',
      slug: 'wane-bameme-bienvenu',
        officeKey: 'member.office.stateCouncil',
        summaryKey: 'member.summary.advisor',
      office: 'STATE COUNCIL',
      summary: 'Provides advisory support on administrative and judicial matters.'
    },
    {
      name: 'YAMULAMBA KASONGO Godefroid',
        titleKey: 'member.title.advisor',
      title: 'Advisor',
      email: 'yamulamba@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1777035291/CONS_YAMULAMBA.jpg_1_l8qor3.jpg',
      role: 'advisor',
      slug: 'yamulamba-kasongo-godefroid',
        officeKey: 'member.office.stateCouncil',
        summaryKey: 'member.summary.advisor',
      office: 'STATE COUNCIL',
      summary: 'Provides advisory support on administrative and judicial matters.'
    },
    {
      name: 'MVUEKIANI NDONZUA Alexis',
        titleKey: 'member.title.advisor',
      title: 'Advisor',
      email: 'mvuekiani@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1776602356/CONS._MVUEKIANI_NDONZUAU_ALEXIX.jpg_1_xk74ak.jpg',
      role: 'advisor',
      slug: 'mvuekiani-ndonzua-alexis',
        officeKey: 'member.office.stateCouncil',
        summaryKey: 'member.summary.advisor',
      office: 'STATE COUNCIL',
      summary: 'Provides advisory support on administrative and judicial matters.'
    },
    {
      name: 'TABALA KITENE Faustin',
        titleKey: 'member.title.advisor',
      title: 'Advisor',
      email: 'tabala@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1777035974/CONS._TABALA_copie.jpg_1_p6zaui.jpg',
      role: 'advisor',
      slug: 'tabala-kitene-faustin',
        officeKey: 'member.office.stateCouncil',
        summaryKey: 'member.summary.advisor',
      office: 'STATE COUNCIL',
      summary: 'Provides advisory support on administrative and judicial matters.'
    },
    {
      name: 'MUSEMA KAWATA Achille',
        titleKey: 'member.title.advisor',
      title: 'Advisor',
      email: 'musema@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1776602713/CONSEILLER_MUSEMA_KAWATA_ACHILLE.jpg_1_ejb0n4.jpg',
      role: 'advisor',
      slug: 'musema-kawata-achille',
        officeKey: 'member.office.stateCouncil',
        summaryKey: 'member.summary.advisor',
      office: 'STATE COUNCIL',
      summary: 'Provides advisory support on administrative and judicial matters.'
    },
    {
      name: 'MUNEKAYI CTTOKO Honoré',
        titleKey: 'member.title.advisor',
      title: 'Advisor',
      email: 'munekayi@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1776771072/CONS_MUNEKAI_copie.jpg_1_mq0xwv.jpg',
      role: 'advisor',
      slug: 'munekayi-cttoko-honore',
        officeKey: 'member.office.stateCouncil',
        summaryKey: 'member.summary.advisor',
      office: 'STATE COUNCIL',
      summary: 'Provides advisory support on administrative and judicial matters.'
    },
    {
      name: 'Mme IBA MAYA Sophie',
        titleKey: 'member.title.advisor',
      title: 'Advisor',
      email: 'iba.maya@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1776602978/CONSEILLERE_IBA_MAYA_SOPHIE_copie.jpg_1_fdffz5.jpg',
      role: 'advisor',
      slug: 'mme-iba-maya-sophie',
        officeKey: 'member.office.stateCouncil',
        summaryKey: 'member.summary.advisor',
      office: 'STATE COUNCIL',
      summary: 'Provides advisory support on administrative and judicial matters.'
    },
    {
      name: 'Mme KULULU NSUNGU Philomène',
        titleKey: 'member.title.advisor',
      title: 'Advisor',
      email: 'kululu@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1776603981/Sans_titre-1.jpg_1_ecrqog.jpg',
      role: 'advisor',
      slug: 'mme-kululu-nsungu-philomene',
        officeKey: 'member.office.stateCouncil',
        summaryKey: 'member.summary.advisor',
      office: 'STATE COUNCIL',
      summary: 'Provides advisory support on administrative and judicial matters.'
    },
    {
      name: 'KAKUDJI WA KAKUDJI',
        titleKey: 'member.title.advisor',
      title: 'Advisor',
      email: 'kakudji@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1777380920/CONS_KAKUDJI_copie.jpg_1_rsqv23.jpg',
      role: 'advisor',
      slug: 'kakudji-wa-kakudji',
        officeKey: 'member.office.stateCouncil',
        summaryKey: 'member.summary.advisor',
      office: 'STATE COUNCIL',
      summary: 'Provides advisory support on administrative and judicial matters.'
    },
    {
      name: 'DJONGESONGO OHUMAHUMA Gaston',
        titleKey: 'member.title.advisor',
      title: 'Advisor',
      email: 'djongesongo@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1776204074/CONS_DJONGESONGE..jpg_pgcxyr.jpg',
      role: 'advisor',
      slug: 'djongesongo-ohumahuma-gaston',
        officeKey: 'member.office.stateCouncil',
        summaryKey: 'member.summary.advisor',
      office: 'STATE COUNCIL',
      summary: 'Provides advisory support on administrative and judicial matters.'
    },
    {
      name: 'SOKO MABIALA',
        titleKey: 'member.title.advisor',
      title: 'Advisor',
      email: 'soko@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1776601461/CONS_SOKO_MABIALA.jpg_1_eu4dig.jpg',
      role: 'advisor',
      slug: 'soko-mabiala',
        officeKey: 'member.office.stateCouncil',
        summaryKey: 'member.summary.advisor',
      office: 'STATE COUNCIL',
      summary: 'Provides advisory support on administrative and judicial matters.'
    },
    {
      name: 'Mme KATALA MATADI Lysette',
        titleKey: 'member.title.advisor',
      title: 'Advisor',
      email: 'katala@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1777380589/CONS._KATALA_copie.jpg_1_b02qbl.jpg',
      role: 'advisor',
      slug: 'mme-katala-matadi-lysette',
        officeKey: 'member.office.stateCouncil',
        summaryKey: 'member.summary.advisor',
      office: 'STATE COUNCIL',
      summary: 'Provides advisory support on administrative and judicial matters.'
    },
    {
      name: 'Mme LUVANGU NKENGE Thérèse',
        titleKey: 'member.title.advisor',
      title: 'Advisor',
      email: 'luvangu@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1776903349/CONS._LUVANGU_copie.jpg_1_vzvygk.jpg',
      role: 'advisor',
      slug: 'mme-luvangu-nkenge-therese',
        officeKey: 'member.office.stateCouncil',
        summaryKey: 'member.summary.advisor',
      office: 'STATE COUNCIL',
      summary: 'Provides advisory support on administrative and judicial matters.'
    },
    {
      name: 'EKABELA MUNDONGYA Ruphin',
        titleKey: 'member.title.advisor',
      title: 'Advisor',
      email: 'ekabela@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1777295346/CONS_EKABELA.jpg_1_u2fmxe.jpg',
      role: 'advisor',
      slug: 'ekabela-mundongya-ruphin',
        officeKey: 'member.office.stateCouncil',
        summaryKey: 'member.summary.advisor',
      office: 'STATE COUNCIL',
      summary: 'Provides advisory support on administrative and judicial matters.'
    },
    {
      name: 'KITWA NDALAMBA Arthur',
        titleKey: 'member.title.advisor',
      title: 'Advisor',
      email: 'kitwa@conseildetatrdc.com',
      image: 'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1776601806/CONS._KITWA_NDALAMBA_ARTHUR.jpg_1_mcuwot.jpg',
      role: 'advisor',
      slug: 'kitwa-ndalamba-arthur',
        officeKey: 'member.office.stateCouncil',
        summaryKey: 'member.summary.advisor',
      office: 'STATE COUNCIL',
      summary: 'Provides advisory support on administrative and judicial matters.'
    }
  ];

  readonly presidents = this.members.filter((member) => member.role === 'president');
  readonly advisors = this.members.filter((member) => member.role === 'advisor');

  readonly honoraryFirstPresidents: Member[] = [
    {
      name: 'Marthe ODIO NONDE',
      title: 'Honorary First President',
        titleKey: 'member.title.honoraryFirstPresident',
      email: 'contact@conseildetatrdc.com',
      image:
        'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1772554526/Marthe_ODIO_NONDE.jpg_1_pzymzp.jpg',
      role: 'president',
      slug: 'marthe-odio-nonde',
      office: 'STATE COUNCIL - HONORARY',
        officeKey: 'member.office.stateCouncilHonorary',
      summary:
        'Served as First President of the State Council from 2022 to 2025 and contributed to institutional consolidation.',
      summaryKey: 'member.summary.odioNonde',
    },
    {
      name: 'Felix VUNDUAWE te PEMAKO',
        titleKey: 'member.title.honoraryFirstPresident',
      title: 'Honorary First President',
      email: 'contact@conseildetatrdc.com',
      image:
        'https://res.cloudinary.com/dhqvb8wbn/image/upload/v1772552204/F%C3%A9lix_VUNDUAWE_te_PEMAKO..jpg_1_usgopn.jpg',
      role: 'president',
      slug: 'felix-vunduawe-te-pemako',
        officeKey: 'member.office.stateCouncilHonorary',
      office: 'STATE COUNCIL - HONORARY',
      summary:
        'Served as First President of the State Council from 2018 to 2022 and helped establish the Court in its early years.',
      summaryKey: 'member.summary.vunduawe',
    }
  ];

  getBySlug(slug: string): Member | null {
    return (
      this.members.find((member) => member.slug === slug) ??
      this.honoraryFirstPresidents.find((member) => member.slug === slug) ??
      null
    );
  }
}


